import type { Metadata } from "next";
import "#/styles/globals.css";
import Header from "#/components/header";
import Footer from "#/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col items-center justify-between p-24 bg-green-400">
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
